//localhost
### Get all customers
Get http://localhost:3000/customers

### Get customer by ID
Get http://localhost:3000/customers/65cef6c726e9cc3828e6c44e

### Create customer
Post http://localhost:3000/customers HTTP/1.1
Content-Type: application/json

{
    "username":"customer4",
    "phone": "4566543210",
    "email": "customer4@customer.com",
    "fullname": "Jill Four",
    "favcolor": "Pink",
    "state": "Nevada"
}

### PUT customer
PUT http://localhost:3000/customers/65cef6c726e9cc3828e6c44e HTTP/1.1
Content-Type: application/json

{
    "phone": "4569873210",
    "email": "customerNew3@customer.com",
    "fullname": "Mike New Three",
    "favcolor": "bright orange",
    "state": "Colorado I think"
}

### DELETE customer
DELETE http://localhost:3000/customers/65cfd6fb6e0d7fc5bcb6c5dc HTTP/1.1